name: Cache Workflow
# trigger workflow again

on:
  push:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache dependencies
      
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-cc9a316

      # Required grading step
      - name: prime-cache-cc9a316
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache HIT"
          else
            echo "Cache MISS"
          fi

      # Create something to cache
      - name: Create cache content
        run: |
          mkdir -p ~/.cache/demo
          echo "cached data" > ~/.cache/demo/file.txt
